### ISSUE TITLE
Support for Sierra?

### ISSUE THREAD

**Issue by LukaJankovic** [xinyuwufei/X1Yoga-Hackintosh#1]

**Comment by xinyuwufei** [comment]
currently I couldn't find a reason to update 10.12 but anyway I will upload config for 10.12.3 shortly.
:‑)

**Comment by LukaJankovic** [comment]
Thanks!! Highly appreciated!

**Comment by kgnss73** [comment]
Hi!

I am very happy and grateful to have found your x1 yoga material.
Recently I am trying to install Sierra in my x1 yoga.

X1 yoga is attempting multi boot on one ssd. I installed Sierra and installed Windows 10, but I do not have multi-boot. (I installed clover on ssd but I do not see the clover boot loader on coms.) My ssd is Samsung 950pro nvme. Is it correct to install Sierra in efi mode or mbr?

In addition, Sierra 10.12.x of the attached document is the data of the sierra ssd installed in the efi folder and then paste it?
I would like advice on how to install x1 yoga.

**Comment by xinyuwufei** [comment]
in your case, the safest plan is : you need a  usb stick for (clover) boot loader and os image and install to an external hdd then, ccc it to your nvme ssd

**Comment by kgnss73** [comment]
Thank you for answer.
The nvme problem has been resolved.
Currently, the problem with the WLAN dw1560 and graphics HD520 still remains.
The wireless LAN has been replaced with the BCM94352z. I can not even patch it.
In general, patching config.plist in 10.11.x fails.

**Comment by kgnss73** [comment]
Hi?
We are preparing a x1 yoga hackintosh through github.
I am trying many times and I want to start over again.
I wonder how you set the bios setting.
Installation has failed for several months and needs your help.
Please let us know the bios setting value when starting from the beginning.
Thank you for your help.

2017-08-02 3:19 GMT+09:00 XinyuWufei <notifications@github.com>:

**Comment by kgnss73** [comment]
My x1 yoga is trying to multi-boot Windows 10 and Sierra.
Currently, Samsung ssd 950pro is divided into two and Windows 10 is
installed in one and Sierra is installed in the other. I am modifying
config.plist to grab the graphics hd520 configuration. It is wrong and I
can not boot to Sierra.
I am trying to install it by reinstalling usb, but when I boot up the usb,
the clover entry screen is broken and the installation is difficult.
I want to go back to the beginning, but I was wondering about the bios
setting.
Please let me know the bios setting value.
Thank you.

2017-12-04 22:43 GMT+09:00 김근창 <kgnss73@gmail.com>:

**Comment by kgnss73** [comment]
I am installing Sierra for several months x1 yoga, but there are a lot of
troubles to install.
Please help me.
Thank you.

2017-12-04 23:00 GMT+09:00 김근창 <kgnss73@gmail.com>:

**Comment by xinyuwufei** [comment]
Those are what I changed, the first one I think is not necessary.
* BIos:
  * Config
      *  F1-F12 as Primary Function:  Disabled
  * Security
       * Secure Boot: Disabled

   * Startup
      * UEFI/Legacy Boot: UEFI Only
        * CSM Support: No

*  I'm not sure what happened to your installation.
   *  did you already installed to your SSD and now I facing the graphics issue?

**Comment by kgnss73** [comment]
Thank you very much for your reply.
I installed Sierra, but I was facing graphics problems.
I touched config.plist to solve the graphics problem and it became
impossible to boot up.
I do not know why, but the installation still fails with usb
We are now trying to reinstall usb and install it again.
But ... it is failing.
(I installed the Elciption on Windows 10 from vmware, I got Sierra from
Absenor, and then I created usb with unibeast.)
I panic before entering the installation screen. First time
ㅠ.
Graphics hd520 It's really hard to catch.

2017-12-06 8:25 GMT+09:00 XinyuWufei <notifications@github.com>:

**Comment by kgnss73** [comment]
Hi?
I have a question.
Do not try to install a high sierra on x1 yoga?
I have recently updated the BIOS, but I have not been able to boot or
reinstall it.
I do not know how.
I would like to try installation of Hi Sierra.

2017-12-06 22:18 GMT+09:00 김근창 <kgnss73@gmail.com>:
