### ISSUE TITLE
Cannot install with Block Sign

### ISSUE THREAD

**Issue by zsxsoft** [xinyuwufei/X1Yoga-Hackintosh#2]
## Environment
ThinkPad X1 Carbon 4th Gen / i7-6600U / 16G / sm961a / Clover + GPT
Clover: Clover_v2.4k_r4035.zip
System: Macos 10.12.1(16B2657) Sierra Installer

## My step
Converted movable drive(128G) to GPT, and created EFI(300MB), MSP, Install Partition(8G). Used ``Leopard hd install helper v0.3`` to extract cdr file to the 8G partition.

Then, I copied the entire ``10.12.X/CLOVER`` to ``EFI/CLOVER``(as the following screenshot). 
![image](https://cloud.githubusercontent.com/assets/2398785/24398492/34e76dd4-13dc-11e7-9409-bd3eb0c2b1a3.png)

Now, the Clover can be booted correctly. I booted the Installer directly, and I got:
``Unable to find the driver for this platform: ACPI``
![image](https://cloud.githubusercontent.com/assets/2398785/24398722/16fa5808-13dd-11e7-9594-f3da031e85a5.png)

And I entered "config" and used "config-Installion.plist" to boot.  Then I got a block sign:
![image](https://cloud.githubusercontent.com/assets/2398785/24398576/8ae384ac-13dc-11e7-8bea-0c03cd6a1222.png)

Before the sign appeared, I took the photo and got the error message:
![image](https://cloud.githubusercontent.com/assets/2398785/24398593/9bb1733e-13dc-11e7-8014-3252539602cd.png)

I even tried ``-v -x -f acpi=off``, but it's seems useless.. And I have no solution yet...

**Comment by xinyuwufei** [comment]
even if our laptops' model is exactly same, as Rehabman said before, it is not recommended to use others' customized aml files directly.
installation step should be as simple as possible and my suggestions are:
* change config-Installion.plist to config.plist first
* keep your  ACPI CLOVER/ACPI/origin and patched folder empty for installation
