### ISSUE TITLE
"Couldn't Unmount Disk"Error , OS installed in a removable 2.5' HDD

### ISSUE THREAD

**Issue by memphisyu** [xinyuwufei/X1Yoga-Hackintosh#3]
Thinkpad X1 Yoga , i7-6600U/16G RAM/SM961 MZVKV512/2k Touch Screen
-------------------------------------------------------------------------------------
Clover-v2.4k-4045
Mac OS X 10.12.3 DMG flash with a 32GB flash drive，Clover/EFI Copied to flash drive EFI partition.
-------------------------------------------------------------------------------------
1st I tried to install the OS X 10.12.3 with Clover+GPT directly in my NVMe SSD, But ended up with "Couldn't Unmount Disk"Error at the end of installation.

Then I tried to covert install the Sierra in a Removable 2.5' Seagate HDD, converted to GPT, with EFI Partition with 300MB. And same issue occured again.

So i wonder if I should remove HackrNVMeFamily-10_12_3.kext and SSDT-NVMe.aml at first place, change config.plist . Could this resolve this Problem?  

After installed in the Removable HDD, then ues the MAC tools to clone the partition to NVMe SSD, then patch HackrNVMeFamily-10_12_3.kext and SSDT-NVMe.aml.

**Comment by xinyuwufei** [comment]
maybe there's a misunderstanding 
CCC is actually short for **Carbon Copy Cloner** which is a free-trial software allows you copy the entire system form Removable HDD to your NVME SSD
once you finished installation on HDD, use the config to verify if the system can recognize the NVME SSD. if so, CCC it!
Good Luck!

**Comment by xinyuwufei** [comment]
[more helpful info](http://www.insanelymac.com/forum/topic/312803-patch-for-using-nvme-under-macos-sierra-is-ready/?p=2368338)

**Comment by memphisyu** [comment]
Thanks for u help, I understand the meaning of CCC, but I prefer the recover function that apple provide in Mac disk tools.
But still, the question reminds as i tried to install 10.12.3 in a Removable HDD, the "Couldn't Unmount Disk"Error also occurred to me.
I just read the more info link you give me on insanelymac.com, found out that if i want to use class-code spoof in further installing, i have to already had a working Mac environment on other partition to create that spoof.
So it's seems an no go task for me to continue.

BTW, Could the 10.12.4 also encounter the "Couldn't Unmount Disk"Error?
Or should i need to install the older version of 10.12.2 to avoid the "Couldn't Unmount Disk"Error, and then use the class-code spoof to upgrade to the latest 10.12.4 version?

**Comment by xinyuwufei** [comment]
oh i see. sounds weird
try to install a simple version to a hdd first eg.: only keeps the necessary config settings and kexts, if you are not sure about it, I can upload a folder to the repo

**Comment by memphisyu** [comment]
thanks, waiting for u folder for another test.
I'm not sure whether or not this has anything to do with USB 3.0 or 2.0 USB Drive or port? I use all USB 3.0 port and Flash Drive/HDD.
Also should i put any related code in KernelAndKextPatches section for HackrNVMeFamily-10_12_4.kext to perform?

**Comment by memphisyu** [comment]
Dleted  HackrNVMeFamily-10_12_3.kext and SSDT-NVMe.aml, and edited config.plist. 
Now Problem Sovled.
Installed in Removable HDD Completed, and CCC also doing great.
Mac OS can detect NVMe SSD, also TRIM is enabled.
But except when open launchpad, the animation seems to freeze, the screen running in a very high lantency, every move in launchpad is freaking slow, this is killing me. But when i choose one app or exit the launchpad, the high lantency disappeared, everything running in normal speed.
Is there something wrong with the HD520？SSDT-IGPU-T460.aml？

**Comment by xinyuwufei** [comment]
for the  final config, did you rename and use the config-postInstallation.plist?

**Comment by memphisyu** [comment]
No，i miss that one.
So，Should i just need to rename the config-plist back to config-installation.plist first ?
and then rename the config-postInstallation.plist as config.plist?

**Comment by xinyuwufei** [comment]
yes, actually clover only requires one config file, and after you finish the installation, you can remove config-installation.plist.

**Comment by memphisyu** [comment]
yes,after rename  config-postInstallation.plist to config.plist, HD520 have 1524MB, and system running smoothly. Everything seems ok，and the mac startup screen not flash again.
But i Also added SSDT-NVMe.aml in SortedOrder, otherwise the system will not be started, because i CCC the partition to NVMe SSD already.

One last question, because i'm using Intel 8260ac wireless card right now, and the recently purchased DW1830 not coming yet, so i need a stable Ethernet connection right now, but after i patch  IntelMausiEthernet.kext through Kext_Utility, the Ethernet card still can't be recognized.

So is there any way to use Ethernet connection？

**Comment by xinyuwufei** [comment]
config-postInstallation.plist has the SSDT-NVMe.aml setting on sortedOrder section.
for ethernet,is off topic, not sure how did you plug it in, i use a mac compatible usb ethernet adaptor which works oob and normally IntelMausiEthernet.kext should work

**Comment by memphisyu** [comment]
I'm using a Onelink+ to RJ45 adapter to connecting the Ethernet.
I found another Ethernet kext which is called AppleIntelE1000e.kext, using this one can have 100M full duplex connection.
And also the reason why there is no SSDT-NVMe.aml setting on sortedOrder section in config-postInstallation.plist, is because i deleted it in the first place, afraid that it could ruin the installation in Removable HDD.
