### ISSUE TITLE
Sleep issues

### ISSUE THREAD

**Issue by LukaJankovic** [xinyuwufei/X1Yoga-Hackintosh#5]
A few things about sleep:
* Closing the lid does not make the computer sleep. But that's okay I set a sleep timeout to 1 minute and it's fine
* After returning from sleep, the fan kicks, even though the temperature of the CPU is blow 50. Is this a known issue? I'm running El Capitan, will updating to Sierra fix it? (I would rather not update because of the brightness issue). Also, can I fix it by tweaking the power management SSDT?

**Comment by LukaJankovic** [comment]
Still happening in Sierra. But I already reverted to El Cap due to HiDPi not working (it's crucial to me since I own the 1440p model)

**Comment by LukaJankovic** [comment]
I fixed it with my own DSDT + SSDTs

**Comment by xinyuwufei** [comment]
if I didn't remember wrong,to me the noisy fun after sleep is related to bios settings
