### ISSUE TITLE
X1 Yoga WQHD and AC8260 Wifi

### ISSUE THREAD

**Issue by jorgeccastro** [xinyuwufei/X1Yoga-Hackintosh#6]
hello. i can't seem to fix the intel graphics kernel panic and also can't get wifi to work... any help?

thanks a lot

**Comment by LukaJankovic** [comment]
Do you have IntelGraphicsDVMTFixup + Lilu kexts?

**Comment by jorgeccastro** [comment]
yes graphics work now, thanks. just can't get the backlight working. aparently everything is done correctly

**Comment by jorgeccastro** [comment]
fixed backlight... any chance of getting usb 3.0 working?

**Comment by LukaJankovic** [comment]
what do you mean? is USB working for you at all?

**Comment by LukaJankovic** [comment]
Oh btw, AC8260 wifi is intel so it will not work with macOS. You need to buy a broadcom card.

**Comment by jorgeccastro** [comment]
yeah, i came to that conclusion yesterday. i can get it for 30$ so... it's manageable. thanks for tip though.

**Comment by jorgeccastro** [comment]
i'm getting fans at max speed after sleep... any fix?

**Comment by LukaJankovic** [comment]
That's werid. No idea sorry ¯\_(ツ)_/¯. Maybe check out [Intel HWP](http://www.insanelymac.com/forum/topic/319775-release-hwp-intel-speed-shift-on-skylake-and-up-enabler-kext/) (if that's still relevant, idk. Sorry I'm not running macOS on my yoga anymore so idk how much I can help)

**Comment by jorgeccastro** [comment]
i'll give it a shot. thanks anyway buddy!

**Comment by vizv** [comment]
Lenovo won't allow you install any WiFi card not on their whitelist.
You may want to buy one BCM94352Z and replace your Intel WiFi card (works on my X1 Yoga Gen 2).

**Comment by jorgeccastro** [comment]
yes already bought the BCM94352Z to see if it works! when i get i'll try!

**Comment by LukaJankovic** [comment]
It should work - it did for me

**Comment by jorgeccastro** [comment]
just got the wifi card but it's the wrong size... does anyone have the Lenovo FRU part number for the part compatible with the X1 Yoga?? thanks

**Comment by xinyuwufei** [comment]
lenovo no longer has the constraints for wifi white list which means you also can use other producers for BCM94352Z

**Comment by jorgeccastro** [comment]
But I can only find the wrong sized card... At least in Europe 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: XinyuWufei <notifications@github.com> Date: 08/02/2018  18:52  (GMT+00:00) To: xinyuwufei/X1Yoga-Hackintosh <X1Yoga-Hackintosh@noreply.github.com> Cc: jorgeccastro <jorgeccastro@gmail.com>, Author <author@noreply.github.com> Subject: Re: [xinyuwufei/X1Yoga-Hackintosh] X1 Yoga WQHD and AC8260 Wifi (#6) 
lenovo no longer has the constraints for wifi white list which means you also can use other producers for BCM94352Z

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xinyuwufei/X1Yoga-Hackintosh","title":"xinyuwufei/X1Yoga-Hackintosh","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xinyuwufei/X1Yoga-Hackintosh"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xinyuwufei in #6: lenovo no longer has the constraints for wifi white list which means you also can use other producers for BCM94352Z"}],"action":{"name":"View Issue","url":"https://github.com/xinyuwufei/X1Yoga-Hackintosh/issues/6#issuecomment-364211635"}}}

**Comment by jorgeccastro** [comment]
just to close the issue, just got the card installed... and everything works... ;) thanks
