### ISSUE TITLE
Wifi card switch impossible now?

### ISSUE THREAD

**Issue by LukaJankovic** [xinyuwufei/X1Yoga-Hackintosh#7]
Hello,

Recently I decided to hackintosh my yoga again, but I noticed that the 94352z wifi card wasn't detected in linux using lspci. In fact, I tried 3 of them and none of them worked! I also tried some killer cards and they worked. Did Lenovo blacklist Broadcom cards in a recent BIOS update? I've tried 1.29, 1.31 and 1.36 and none of them worked.

**Comment by vizv** [comment]
Haven't update my BIOS yet, Is your laptop X1 Yoga Gen 2? I saw the latest BIOS version is [1.28](https://pcsupport.lenovo.com/ca/en/products/LAPTOPS-AND-NETBOOKS/THINKPAD-X-SERIES-LAPTOPS/THINKPAD-X1-YOGA-TYPE-20JD-20JE-20JF-20JG/downloads/DS121063)

**Comment by LukaJankovic** [comment]
No I have the 1st gen, 20FQ

**Comment by willin** [comment]
我比较好奇想入手，就不知道 4G WWAN 卡能不能驱动了。。。

**Comment by LukaJankovic** [comment]
No, not in macOS as far as I know. Also, there is no issue, it just appears that my connection was loose and so the card wasn't being detected.
